<?php
$e=fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$fecha=fn($v)=>$v?date('d/m/Y',strtotime((string)$v)):'';
?>
<style>body{font-family:Arial,sans-serif;font-size:10px;color:#222}.top{border-top:12px solid #10acd6;padding-top:18px}.title{text-align:right;color:#17637e;font-size:18px;font-weight:bold}.sub{color:#17637e;font-weight:bold}.box{border:1px solid #333;margin:12px 0}.head{background:#17637e;color:#fff;font-weight:bold;padding:6px}.row{padding:5px;border-top:1px solid #777}.label{font-weight:bold}.grid{width:100%;border-collapse:collapse}.grid th,.grid td{border:1px solid #444;padding:5px}.grid th{background:#e8e8e8}.small{font-size:8px;text-align:justify}.sign{margin-top:24px}</style>
<div class="top"><div class="title">FORMATO RETROALIMENTACIÓN</div><div class="title" style="font-size:11px">Línea ICBF</div>
<div class="box"><div class="head">DATOS PERSONALES DEL COLABORADOR</div><div class="row"><span class="label">Nombre completo:</span> <?=$e($paquete['agente_nombre']??'')?></div><div class="row"><span class="label">Cédula:</span> <?=$e($paquete['gcp_agente_id']??'')?></div><div class="row"><span class="label">Fecha y hora de elaboración:</span> <?=$e($paquete['gcp_registro_fecha']??date('Y-m-d H:i:s'))?></div></div>
<div class="box"><div class="head">OPORTUNIDAD DE MEJORA (Documenta jefe inmediato)</div><div class="row"><span class="label">Indicador:</span> <?=$e($paquete['gci_nombre']??'')?></div><div class="row"><span class="label">Metodología:</span> <?=$e($retro['gcr_metodologia']??'')?></div><div class="row"><span class="label">Causa raíz:</span><br><?=nl2br($e($retro['gcr_causa_raiz']??''))?></div><div class="row"><span class="label">Estrategia correctiva y/o de mejora:</span><br><?=nl2br($e($retro['gcr_estrategia_correctiva']??''))?></div></div>
<div class="box"><div class="head">COMPROMISOS PACTADOS (Documenta colaborador)</div><div class="row"><span class="label">Compromiso frente a la falta:</span><br><?=nl2br($e($respuesta['gcra_compromiso_general']??''))?></div><div class="row"><span class="label">Acciones para la no reincidencia:</span><br><?=nl2br($e($respuesta['gcra_acciones_no_reincidencia']??''))?></div><div class="row"><b>Qué:</b> <?=$e($respuesta['gcra_que']??'')?> &nbsp; <b>Cómo:</b> <?=$e($respuesta['gcra_como']??'')?> &nbsp; <b>Cuándo:</b> <?=$fecha($respuesta['gcra_cuando']??'')?></div><div class="row"><span class="label">Aspectos relevantes:</span><br><?=nl2br($e($respuesta['gcra_aspectos_relevantes']??''))?></div><div class="row"><b>¿El ejercicio fue claro y le permitirá mejorar?</b> <?=!empty($respuesta['gcra_confirma_claridad'])?'Sí':'No'?></div></div>
<div class="box"><div class="head">ENCUESTA DEL ESPACIO</div><table class="grid"><tr><th>¿CUÁL ES TU PERCEPCIÓN DE LA RETROALIMENTACIÓN?</th><th>Valor</th></tr><?php foreach(($encuesta['respuestas']??[]) as $r):?><tr><td><?=$e($r['gcep_pregunta'])?></td><td style="text-align:center"><?=$e($r['gcer_valor'])?></td></tr><?php endforeach;?></table></div>
<p>Cordialmente,</p><p><b>Supervisor:</b> <?=$e($paquete['supervisor_nombre']??'')?></p><div class="sign">____________________________________<br>Firma / aceptación electrónica<br><b>Nombre del colaborador:</b> <?=$e($paquete['agente_nombre']??'')?><br><b>Fecha y hora cierre de paquete:</b> <?=$e($paquete['gcp_fecha_cierre']??'')?></div>
<p class="small"><b>Nota:</b> La aprobación de cierre del paquete coaching certifica que el colaborador fue notificado, orientado y retroalimentado adecuadamente, y que conoce los compromisos definidos para sus indicadores y actividades laborales.</p></div>
